<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
$_code=$this->getMethodCode();
?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
         <li>
            <a id="more_info_<?php echo $_code; ?>" href="http://bb.com.br/portalbb/page44,3766,2229,0,0,1,2.bb" target="_blank"><?php echo __('More information about Bancodobrasil') ?></a>
        </li>
    </ul>
</fieldset>
<div>
</div>